### ISSUE TITLE
Archive the repository

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/galata#81]
With https://github.com/jupyterlab/jupyterlab/pull/10796 now merged upstream, we should be able to archive this repo to clearly communicate where the main development is happening.

### TODO

- [x] Transfer relevant issues to https://github.com/jupyterlab/jupyterlab
- [x] Add an archive header to the README.md: #82 
- [ ] Archive the repo

**Comment by fcollonval** [comment]
About the issues, the remaining ones are:

- #23 --> Can be transferred
- #32 --> No transfer (link to user usage)
- #47 --> No transfer as not relevant
- #65 --> As we rely now on Playwright HTML report, we could submit the suggestion upstream
- #68 --> Can be transferred
- #74 --> To close
- #77 --> Can be transferred and suggested as new helper

**Comment by mbektas** [comment]
I closed the remaining issues. Once we merge the open MR and publish new version, we are good to archive I think. Thanks for all the hard work @fcollonval and @jtpio!

**Comment by jtpio** [comment]
@mbektas would you like to proceed with the `3.0.11-4` release?

**Comment by mbektas** [comment]
sure, I will do that and update here once done.

**Comment by mbektas** [comment]
I just published `@jupyterlab/galata@3.0.11-4`, good to archive this project now!

**Comment by jtpio** [comment]
Nice, thanks @mbektas!

**Comment by jtpio** [comment]
Proceeding with the archiving now. Thanks all!
